# Generated by Django 2.0.2 on 2018-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_port',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
